# Generated by Django 4.1 on 2025-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0054_alter_dataassessmentresult_activatedby_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="freetextannotation",
            field=models.TextField(
                blank=True,
                help_text="(free text annotation)",
                null=True,
                verbose_name="free text annotation",
            ),
        ),
    ]
