# Generated by Django 4.1 on 2025-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0055_pairwiseassessmentresult_freetextannotation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="freetextannotation",
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="other_text",
            field=models.TextField(
                blank=True,
                help_text='Free text for "Other" option',
                null=True,
                verbose_name="Other text",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="selected_choices",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated selected options",
                max_length=255,
                null=True,
                verbose_name="Selected choices",
            ),
        ),
    ]
