# Generated by Django 4.1 on 2025-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EvalData",
            "0056_remove_pairwiseassessmentresult_freetextannotation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="other_wikipedia_contribution_text",
            field=models.TextField(
                blank=True,
                help_text="Other way of contributing to Wikipedia",
                null=True,
                verbose_name="Other Wikipedia contribution",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="wikipedia_contributions",
            field=models.CharField(
                blank=True,
                help_text="How do you contribute to Wikipedia?",
                max_length=255,
                null=True,
                verbose_name="Wikipedia contributions",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="wikipedia_duration",
            field=models.CharField(
                blank=True,
                help_text="How long have you contributed to Wikipedia?",
                max_length=50,
                null=True,
                verbose_name="Wikipedia contribution duration",
            ),
        ),
    ]
