# Generated by Django 4.1 on 2025-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EvalData",
            "0057_pairwiseassessmentresult_other_wikipedia_contribution_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="selected_translation",
            field=models.CharField(
                blank=True,
                help_text="The translation choice selected by the user (Option1 or Option2)",
                max_length=255,
                null=True,
                verbose_name="Selected translation",
            ),
        ),
    ]
