# Generated by Django 4.1 on 2025-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0058_pairwiseassessmentresult_selected_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="other_wikipedia_contribution_text",
        ),
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="wikipedia_contributions",
        ),
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="wikipedia_duration",
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="feedback_options",
            field=models.CharField(
                blank=True,
                help_text="What is something we can do better next time?",
                max_length=255,
                null=True,
                verbose_name="Feedback options",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="fluency_in_target_language",
            field=models.CharField(
                blank=True,
                help_text="How would you rate your fluency in the target language?",
                max_length=50,
                null=True,
                verbose_name="Fluency or proficiency in target language",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="other_feedback_options_text",
            field=models.TextField(
                blank=True,
                help_text="Other - What is something we can do better next time?",
                null=True,
                verbose_name="Other feedback options",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="other_wikipedia_familiarity_text",
            field=models.TextField(
                blank=True,
                help_text="Other - How familiar are you with Wikipedia?",
                null=True,
                verbose_name="Other Wikipedia familiarity",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="overallExperience",
            field=models.CharField(
                blank=True,
                help_text="How would you rate your overall experience?",
                max_length=50,
                null=True,
                verbose_name="Overall experience",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="wikipedia_familiarity",
            field=models.CharField(
                blank=True,
                help_text="How familiar are you with Wikipedia?",
                max_length=255,
                null=True,
                verbose_name="Wikipedia familiarity",
            ),
        ),
    ]
