# Generated by Django 4.1 on 2025-04-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EvalData",
            "0059_remove_pairwiseassessmentresult_other_wikipedia_contribution_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="difference_votes",
            field=models.TextField(
                blank=True,
                help_text="User votes for each pairwise difference (which system is better for each difference)",
                null=True,
                verbose_name="Votes for pairwise differences",
            ),
        ),
    ]
