# Generated by Django 4.1 on 2025-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0060_pairwiseassessmentresult_difference_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="difference_votes",
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="span_diff_votes",
            field=models.TextField(
                blank=True,
                help_text="Stores which candidate was preferred for each highlighted difference.",
                null=True,
                verbose_name="Votes for highlighted differences",
            ),
        ),
    ]
