# Generated by Django 4.1 on 2025-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0061_remove_pairwiseassessmentresult_difference_votes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="span_diff_explanations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="span_diff_other_texts",
            field=models.TextField(
                blank=True,
                help_text='User free-text explanations when "Other" is selected.',
                null=True,
                verbose_name="Other text explanations for each diff",
            ),
        ),
    ]
