# Generated by Django 4.1 on 2025-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0062_pairwiseassessmentresult_span_diff_explanations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="span_diff_texts",
            field=models.TextField(
                blank=True,
                help_text="Text spans shown to user during annotation.",
                null=True,
                verbose_name="Span difference texts",
            ),
        ),
    ]
