# Generated by Django 4.1 on 2025-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0063_pairwiseassessmentresult_span_diff_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairwiseassessmentresult",
            name="selected_choices",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated selected options to explain the preferred aggragate translation",
                max_length=255,
                null=True,
                verbose_name="Selected choices",
            ),
        ),
    ]
