# Generated by Django 4.1 on 2025-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvalData", "0063_pairwiseassessmentresult_span_diff_texts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pairwiseassessmentresult",
            name="selected_choices",
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="non_selected_problems",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of problems with the non-selected translation",
                max_length=255,
                null=True,
                verbose_name="Non-selected problems",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="non_selected_problems_other",
            field=models.TextField(
                blank=True,
                help_text='Free text for "Other" option in non-selected problems',
                null=True,
                verbose_name="Other non-selected problems",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="selected_advantages",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of advantages of the selected translation",
                max_length=255,
                null=True,
                verbose_name="Selected advantages",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="selected_advantages_other",
            field=models.TextField(
                blank=True,
                help_text='Free text for "Other" option in selected advantages',
                null=True,
                verbose_name="Other selected advantages",
            ),
        ),
        migrations.AddField(
            model_name="pairwiseassessmentresult",
            name="wiki_adequacy",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of translations adequate for Wikipedia",
                max_length=255,
                null=True,
                verbose_name="Wikipedia adequacy",
            ),
        ),
    ]
